ALTER TABLE "DoctorProfile" ADD COLUMN IF NOT EXISTS "gender" TEXT;
ALTER TABLE "DoctorProfile" ADD COLUMN IF NOT EXISTS "supportsOnline" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "DoctorProfile" ADD COLUMN IF NOT EXISTS "supportsInPerson" BOOLEAN NOT NULL DEFAULT false;
