ALTER TABLE "Appointment"
ADD COLUMN "durationMinutes" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN "type" TEXT NOT NULL DEFAULT 'ONLINE',
ADD COLUMN "price" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "paymentStatus" TEXT NOT NULL DEFAULT 'PENDING';
